# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e49bcaee48e9229da29744414e2e7c4097760921fffd0c3b4c3d3fb82b03c00d33f3ebf471455d5b6bc8258083c5b3d25c37c5ca0e8f66870a82a18c1c3a9ab2

test:
  secret_key_base: 1dea18c953f374de30e45328b2a3c4114a97b255ac2ea25263fbe1f8e6ad2bb0e031115ca11dd303cb6d047898190b21f27e839c49f7f81dd158a197ad1d300f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
